### ISSUE TITLE
Don't have option API on A.I Type

### ISSUE THREAD

**Issue by arifik0502** [doki-doki-ai-edition/Mod#18]
I just downloaded version [v1.3.0-demo](https://github.com/doki-doki-ai-edition/Mod/releases/tag/v1.3.0-demo) on my windows11 Home and yeah it show like this
![Screenshot 2024-09-19 022519](https://github.com/user-attachments/assets/d609b666-6eda-4fbb-b0a0-56990170cb1d)

Btw thanks for your hardwork.... Really appreciate that passion ♡✧˚ ༘ ⋆｡♡˚

**Comment by zeeblo** [comment]
The API option is only available on the Groq version https://github.com/zeeblo/DDAE-Groq

I'm assuming you already figured this out but just incase anyone else is confused.
(also thank you)
